In [2]:
import os
import sys
import importlib
AbsPath = str(os.path.abspath(""))+"/.."
sys.path.append(AbsPath)
import numpy as np 
from Functions import Functions as F

In [5]:
#Abundance Matching Parameters
Override =\
{\
'M10':12.0,\
'SHMnorm10':0.032,\
'beta10':1.5,\
'gamma10':0.56,\
'M11':0.6,\
'SHMnorm11':-0.014,\
'beta11':-2,\
'gamma11':0.08\
}


AbnMtch =\
{\
'Behroozi13': False,\
'Behroozi18': False,\
'B18c':False,\
'B18t':False,\
'G18':False,\
'G18_notSE':False,\
'G19_SE':True,\
'G19_cMod':False,\
'Lorenzo18':False,\
'Moster': False,\
'Moster10': False,\
'Illustris': False,\
'z_Evo':True,\
'Scatter': 0.15,\
'Override_0': False,\
'Override_z': False,\
'Override': Override,\
'PFT': False,\
'M_PFT1': False,\
'M_PFT2': False,\
'M_PFT3': False,\
'N_PFT1': False,\
'N_PFT2': False,\
'N_PFT3': False,\
'b_PFT1': False,\
'b_PFT2': False,\
'b_PFT3': False,\
'g_PFT1': False,\
'g_PFT2': False,\
'g_PFT3': False,\
'g_PFT4': False\
}

Paramaters = \
{\
'AbnMtch' : AbnMtch,\
'AltDynamicalTime': 1,\
'NormRnd': 0.5,\
'SFR_Model': 'CE',\
'PreProcessing': False,\
'AltDynamicalTimeB': False\
}

In [91]:
importlib.reload(F)

<module 'Functions.Functions' from '/data/pg1g15/STEEL/Notebooks/../Functions/Functions.py'>

In [92]:
DM = [10, 11, 12, 13]
for i in range(10):
    M = F.DarkMatterToStellarMass(DM, 0, Paramaters, ScatterOn = True)
    print(M)

[ 5.49673865  8.29987791 10.48181578 10.87777581]
[ 5.63567495  8.44160478 10.33237611 11.28907577]
[ 5.64988365  8.25080523 10.23253347 11.19265116]
[ 5.74999816  8.31724455 10.82741583 11.20594816]
[ 5.65361915  8.32258345 10.75168283 11.22266997]
[ 5.34085312  8.32088393 10.8610058  11.09438757]
[ 5.39047087  8.19657913 10.58309666 11.00593774]
[ 5.65744903  8.41355237 10.59357923 11.44179465]
[ 5.57104847  8.53126604 10.66498562 11.3948693 ]
[ 5.70577329  8.4565234  10.47004556 11.16558201]
